[profile.release]
panic = 'unwind'

[workspace]
members = [
    'node',
    'pallets/template',
    'pallets/identity-extra',
    'pallets/support',
    'pallets/unique-id',
    'pallets/vfe',
    'pallets/currencies',
    'pallets/buyback',
    'runtime/*',
    'primitives',
]
